import streamlit as st
import os
import openai
import requests
import shutil
from PIL import Image

from openai import OpenAI

client = OpenAI()

# Setze den API-Schlüssel
api_key = st.secrets["api"]["api_key"]
assert api_key.startswith('sk-'), 'Error loading the API key. The API key starts with "sk-"'
os.environ['OPENAI_API_KEY'] = api_key

# Initialisiere den OpenAI-Client
#openai.api_key = api_key



def generate_image(prompt):
    response = client.images.create(
        model='dall-e-3',
        prompt=prompt,
        style='vivid',
        size='1024x1024', # 1024x1792, 1792x1024 pixels
        quality='standard',
        n=1
    )
    return response

st.title("DALL-E Image Generator")

prompt = st.text_input("Enter a description for the image:", "A photorealistic image of a ginger cat curled up on a windowsill, gazing out at a bustling city street slick with rain.")

if st.button("Generate Image"):
    with st.spinner('Generating image...'):
        response = generate_image(prompt)
        image_url = response['data'][0]['url']

        image_resource = requests.get(image_url, stream=True)

        if image_resource.status_code == 200:
            image_name = 'dalle3-generated-image.png'
            with open(image_name, 'wb') as f:
                shutil.copyfileobj(image_resource.raw, f)
            
            img = Image.open(image_name)
            st.image(img, caption='Generated by DALL-E 3', use_column_width=True)
        else:
            st.error('Error accessing the image!')

st.write("Note: The image is generated using OpenAI's DALL-E 3 model.")
